import express from "express";
import { adicionarMedico } from "./adicionarMedico.js";
import { adicionarPaciente } from "./adicionarPaciente.js";
import { adicionarConsulta } from "./adicionarConsultas.js";
import { listarMedicos } from "./listarMedicos.js";
import { listarPacientes } from "./listarPacientes.js";
import { listarConsultas } from "./listarConsultas.js";
import { deletarMedico } from "./deletarMedico.js";
import { deletarPaciente } from "./deletarPaciente.js";
import { deletarConsulta } from "./deletarConsultas.js";
import { atualizarMedico } from "./atualizarMedicos.js";
import { atualizarPaciente } from "./atualizarPaciente.js";
import { listarConsultasDeUmMedico } from "./consultasDeUmMedico.js";
import { DadosDaAPI } from "./clinica.js";
import { medicosQueAtenderamPaciente } from "./filtrarPorPaciente.js";
import { ConsultasPorMes } from "./consultasEmUmMesEspecfico.js";
import { filtrarPorMedico } from "./filtrarPorMedico.js";

export const router = express.Router();
router.get("/clinica", DadosDaAPI);
router.get("/clinica/relatorios/medicos/:CRM", filtrarPorMedico)
router.get("/clinica/relatorios/mes/:mes/:ano", ConsultasPorMes);
router.get("/clinica/relatorios/pacientes/:ID", medicosQueAtenderamPaciente);
router.get("/clinica/relatorios/medicos/:CRM", listarConsultasDeUmMedico);
router.put("/clinica/pacientes/:ID", atualizarPaciente);
router.put("/clinica/medicos/:CRM", atualizarMedico);
router.delete("/clinica/consultas/:IDconsulta", deletarConsulta);
router.delete("/clinica/pacientes/:ID", deletarPaciente);
router.delete("/clinica/medicos/:CRM", deletarMedico);
router.get("/clinica/consultas", listarConsultas);
router.get("/clinica/pacientes", listarPacientes);
router.get("/clinica/medicos", listarMedicos);
router.post("/clinica/consultas", adicionarConsulta);
router.post("/clinica/pacientes", adicionarPaciente);
router.post("/clinica/medicos", adicionarMedico);
